# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppleGoogleYandexMaps' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppleGoogleYandexMaps
pod 'GoogleMaps'
pod 'YandexMapsMobile', '4.0.0-full'

end
